CREATE  TABLE 'users'{
'id' INT(11) NOT NULL,
'firstname' VARCHAR (150) NOT NULL,
'lastname' VARCHAR (150) NOT NULL,
'email' VARCHAR (120) NOT NULL,
'phone' INT (11) NOT NULL,
'address' VARCHAR(150) NOT NULL,
'created_at' TIMESTAMP NOT NULL default CURRENT_TIMESTAMP
} ENGINE=INNODB DEFAULT CHARSET=utf8 COLLATE=utf8_persian_ci;

ALTER TABLE 'users'
ADD PRIMARY KEY ('id');
ALTER TABLE 'users'
MODIFIES 'id' INT(11) NOT NULL AUTO_INCREMENT;
COMMIT;